import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ffdad4",
        background: "#351f1b",
        tertiary: "#292421",
        secondary: "#d4c3bf",
        "on-surface": "#fbfbe2",
        "surface-dim": "#4d3430",
        primary: "#fbfbe2",
        "on-tertiary-fixed": "#201a18",
        "tertiary-fixed": "#ece0dc",
        "on-secondary-container": "#795c51",
        "surface-bright": "#4d3430",
        "primary-fixed-dim": "#e3beb8",
        "on-tertiary-fixed-variant": "#4c4542",
        "on-primary-fixed": "#2b1613",
        "surface-tint": "#745853",
        "secondary-fixed": "#ffdbce",
        "on-primary": "#351f1b",
        "on-error": "#ffffff",
        "surface-container-highest": "#5b403c",
        "surface-container": "#4d3430",
        "on-secondary-fixed": "#2b160f",
        "primary-container": "#4d3430",
        surface: "#351f1b",
        "inverse-primary": "#e3beb8",
        "tertiary-fixed-dim": "#cfc4c0",
        "surface-variant": "#504442",
        "on-surface-variant": "#d4c3bf",
        "error-container": "#ffdad6",
        outline: "#827471",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#5b403c",
        "surface-container-high": "#45312d",
        error: "#ba1a1a",
        "surface-container-low": "#3c2a26",
        "inverse-on-surface": "#f2f2d9",
        "secondary-container": "#fed7ca",
        "outline-variant": "#504442",
        "on-tertiary-container": "#aca29f",
        "on-primary-container": "#bf9d97",
        "surface-container-lowest": "#2b1613",
        "secondary-fixed-dim": "#e4beb2",
        "on-secondary-fixed-variant": "#5b4137",
        "on-error-container": "#93000a",
        "inverse-surface": "#303221",
        "tertiary-container": "#403936",
        "on-background": "#fbfbe2",
      },
      fontFamily: {
        headline: ["var(--font-headline)", "serif"],
        body: ["var(--font-body)", "sans-serif"],
        label: ["var(--font-body)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
